apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-github
  labels:
    app: nginx
    srv: lb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx-github
          ports:
          - containerPort: 80
